baseURL = 'https://chdeese.github.io/'
languageCode = 'en-us'
title = 'chdeese.github.io'

[markup.highlight]
noclasses = false
style = "github"

[[module.imports]]
path = "github.com/willfaught/paige"